[build]
  command = "npm run build:netlify"
  publish = ".next"

[build.environment]
  NETLIFY_NEXT_PLUGIN_SKIP = "true"
  NODE_VERSION = "20"
  NEXT_TELEMETRY_DISABLED = "1"
  NETLIFY_USE_YARN = "false"
  # Remove Go version dependency
  GO_VERSION = ""
  # Skip TypeScript checking during build
  DISABLE_ESLINT_PLUGIN = "true"
  SKIP_PREFLIGHT_CHECK = "true"
  GENERATE_SOURCEMAP = "false"

[[plugins]]
  package = "@netlify/plugin-nextjs"

# Ignore TypeScript errors during build (use this temporarily if needed)
[build.processing.js]
  bundle = false
  minify = false

[functions]
  included_files = ["!node_modules/.pnpm/**"]
  node_bundler = "esbuild"

# Handle 404 errors
[[redirects]]
  from = "/*"
  to = "/404"
  status = 404

# Always redirect to HTTPS
[[redirects]]
  from = "http://*"
  to = "https://:splat"
  status = 301
  force = true 